---
#----------------------------------
# Title: soto-composer.yaml
# Author: Victor Soto
# Date: 01/28/2024
# Description: Web420 - Describing an API with an API description format
#----------------------------------

openapi: "3.0.0"
info:
  title: Composer API
  version: "1.0.0"
tags:
  - name: Composers
paths:
  /composers:
    get:
      tags:
        - Composers
      summary: Returns a list of composer documents
      description: API for returning a list of composers from MongoDB Atlas
      operationId: findAllComposers
      responses:
        "200":
          description: Composer documents
        "500":
          description: Server Exception
        "501":
          description: MongoDB Exception
    post:
      tags:
        - Composers
      summary: Creates a new composer object
      description: API for adding new composer objects
      operationId: createComposer
      requestBody:
        description: Composers information
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
      responses:
        "200":
          description: User added
        "500":
          description: Server Exception
        "501":
          description: MongoDB Exception
  /composers/{id}:
    get:
      tags:
        - Composers
      summary: Returns a composer document
      description: API for returning a single composer object from MongoDB
      operationId: findComposerById
      parameters:
        - name: id
          in: path
          required: true
          description: The composerId requested by the user
          schema:
            type: string
      responses:
        "200":
          description: Composer document in JSON format
        "500":
          description: Server Exception
        "501":
          description: MongoDB Exception